# update_data.yml - v1.9.0
name: Automação do Painel DICOM

on:
  schedule:
    - cron: '0 9 * * *' 
  workflow_dispatch: 

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar o repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Instalar dependências
        run: pip install -r requirements.txt

      - name: 4. Executar Motor do Painel
        run: python scraper.py

      - name: 5. Salvar dados incrementais e purga
        run: |
          git config --global user.name "Robo DICOM"
          git config --global user.email "automacao@dicom.ifbaiano"
          git add data/ || echo "Pasta data não encontrada."
          git diff-index --quiet HEAD || git commit -m "⚙️ Atualização Ultimate Analytics (Painel v1.9.0)"
          git push
